### ISSUE TITLE
Creating a shop with same name but a different case on the letters

### ISSUE THREAD

**Issue by spexii** [tswfi/epages_provisioning#27]
* ePages provisioning version: 0.3.0
* ePages version: 11?
* Python version: 3.6.3
* Operating System: Ubuntu 16.04

### Description

I tried to create a shop with same name, but different case on the letters. With exact same name the shop creation fails with an error telling that shop already exists, and that's fine. But if I'm trying to create a shop with same name but different case on the letters, it fails on the init phase already and without error handling.

### What I Did

```
from epages_provisioning.provisioning import ShopConfigService
from epages_provisioning.shop import Shop

# Get the shop config service
sc = ShopConfigService(
    server="http://jaana01.sml18.vilkas.pri",
    provider="Distributor2",
    username="admin",
    password="admin"
)

# Create the first shop

# This wont create the shop yet
shop = Shop("Test", provisioning=sc)

# Shop type is mandatory
shop.ShopType = "MinDemo"

# Create the shop
shop.create()

# Access the shop attributes, and change them as required
shop.IsTrialShop = True

# Apply the changes to the server
shop.apply()

# Secondly, try to create exact same shop again

shop = Shop("Test", provisioning=sc)

shop.ShopType = "MinDemo"

# This line fails with the error Shop already exists
shop.create()

ShopExistsError: Shop already exists

# Thirdly, try to create same shop but a slightly different case

# This fails already here with a fault
shop = Shop("TeSt", provisioning=sc)

zeep.exceptions.Fault: Object /Providers/Distributor2/ShopRefs doesn't contain a child alias
```

**Comment by tswfi** [comment]
http://helpcenter.epages.com/Doc/ver_7_21_0/epages/API/DE_EPAGES/ShopConfiguration/API/Object/Provider.pm.html#existsShop

It seems that ePages does not something strange with the cases for shop aliases.

**Comment by tswfi** [comment]
cantfix. the case confusion happens on ePages side.
